export const EXHORTO_REPOSITORY = Symbol('EXHORTO_REPOSITORY');
export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const BOLETA_HONORARIO_REPOSITORY = Symbol(
  'BOLETA_HONORARIO_REPOSITORY',
);
